// One-line etymologies for common English game words.
// Used by the result card on English wins. Missing entries simply show no card.
const etymologies = {
  "ALARM": "From Italian all'arme, 'to arms.' A medieval call to grab weapons.",
  "ALBUM": "Latin for 'white,' originally a blank tablet for public notices.",
  "ALIEN": "From Latin alienus, 'belonging to another.'",
  "ANGEL": "From Greek angelos, 'messenger.'",
  "APPLE": "Old English æppel, used for any round fruit before being narrowed to one.",
  "AROMA": "Greek aroma, 'spice or sweet herb.'",
  "ARROW": "Old English arwe, related to the word for 'bow.'",
  "BACON": "Old French bacun, originally meaning the back of a pig.",
  "BAGEL": "Yiddish beygl, from a German root meaning 'ring.'",
  "BANJO": "Likely from Kimbundu mbanza, a stringed instrument from West Africa.",
  "BEACH": "Old English bæce, 'stream' or 'pebbles by the water.'",
  "BERRY": "Old English berie, related to words for 'grape.'",
  "BLACK": "Old English blæc, 'dark, ink-colored.'",
  "BLAZE": "Old English blæse, 'torch' or 'bright flame.'",
  "BLEND": "Old Norse blanda, 'to mix.'",
  "BLOOM": "Old Norse blom, 'flower.'",
  "BOARD": "Old English bord, both 'plank' and 'table.'",
  "BRAIN": "Old English bragen, related to Greek words for 'top of the head.'",
  "BRAVE": "From Italian bravo, originally 'wild' or 'untamed.'",
  "BREAD": "Old English bread, originally 'piece of food.'",
  "BREAK": "Old English brecan, 'to shatter.'",
  "BRICK": "Old French brique, from a root meaning 'broken piece.'",
  "BRIDE": "Old English bryd, 'newly married woman.'",
  "BRIEF": "Latin brevis, 'short.'",
  "BROOK": "Old English broc, 'small stream.'",
  "BROWN": "Old English brun, an early color word common across Germanic languages.",
  "BUDDY": "American English, probably a child's pronunciation of 'brother.'",
  "BUILD": "Old English byldan, 'to construct a house.'",
  "CABIN": "From Latin capanna, 'hut.'",
  "CABLE": "Latin capulum, 'a rope used to lead animals.'",
  "CANDY": "From Arabic qandi, 'crystallized sugar.'",
  "CANOE": "From Carib Spanish canoa, the dugout boat encountered in 1492.",
  "CARGO": "Spanish cargo, 'a load,' from Latin carricare.",
  "CEDAR": "From Greek kedros, the resinous evergreen.",
  "CHAIR": "Old French chaiere, ultimately from Greek kathedra, 'seat.'",
  "CHARM": "Latin carmen, 'song' or 'incantation.'",
  "CHEESE": "Old English cese, from Latin caseus.",
  "CHESS": "Old French esches, from Persian shah, 'king.'",
  "CHILD": "Old English cild, 'fetus, infant.'",
  "CHILI": "From Nahuatl chīlli, the Aztec word for the pepper.",
  "CIDER": "From Hebrew shekhar, 'strong drink,' through Greek and Latin.",
  "CITY": "Latin civitas, 'community of citizens.'",
  "CLEAR": "Latin clarus, 'bright, famous.'",
  "CLIFF": "Old English clif, 'steep rock face.'",
  "CLOCK": "Medieval Latin clocca, 'bell,' since early clocks rang the hour.",
  "CLOTH": "Old English clath, originally any cloth or sail.",
  "CLOUD": "Old English clud, originally 'rock' or 'hill.' The shape transferred to the sky.",
  "COACH": "From Kocs, a Hungarian town that made fine carriages in the 1500s.",
  "COMET": "Greek kometes, 'long-haired,' for the trailing tail.",
  "COMIC": "Greek komikos, from komos, a festive procession.",
  "CRANE": "Old English cran. The lifting machine was named for the long-necked bird.",
  "CRAZY": "From craze, 'to break.' A 'crazed' mind was a broken one.",
  "CREAM": "Old French cresme, blending Latin chrisma 'ointment' and Gaulish krama.",
  "CRISP": "Latin crispus, 'curly,' applied to anything crinkled.",
  "CROWN": "Latin corona, 'wreath.'",
  "DAIRY": "Old English dæge, a female servant who made bread and tended cows.",
  "DANCE": "From Old French dancier, of unclear deeper origin.",
  "DEATH": "Old English deað, common across Germanic languages.",
  "DEPOT": "French depot, 'a place where things are deposited.'",
  "DEVIL": "Greek diabolos, 'slanderer.'",
  "DIARY": "Latin diarium, 'daily allowance,' later 'daily record.'",
  "DOZEN": "Old French dozaine, from Latin duodecim, 'twelve.'",
  "DRAFT": "Old English dragan, 'to drag,' the same root as 'draw.'",
  "DREAM": "Old English dream meant 'joy' or 'music' before its meaning shifted.",
  "DRESS": "From Old French dresser, 'to arrange or put straight.'",
  "DRINK": "Old English drincan, related across Germanic languages.",
  "EAGLE": "Old French aigle, from Latin aquila.",
  "EARTH": "Old English eorthe, the soil and the planet share the same word.",
  "EERIE": "Old English earg, 'cowardly,' which evolved to 'inspiring fear.'",
  "EIGHT": "Old English eahta, an ancient number found across Indo-European languages.",
  "ELITE": "French élite, 'chosen,' from Latin eligere.",
  "ELOPE": "Old English aleopan, 'to leap away.'",
  "EMAIL": "Coined in 1982 from electronic + mail.",
  "ENEMY": "Latin inimicus, 'not friend.'",
  "ENJOY": "Old French enjoir, 'to give joy to.'",
  "ENTER": "Latin intrare, 'to go in.'",
  "EQUAL": "Latin aequalis, 'level, even.'",
  "ERROR": "Latin errare, 'to wander or stray.'",
  "ESSAY": "French essai, 'an attempt or trial.' Coined in writing by Montaigne in 1580.",
  "EVENT": "Latin eventus, 'outcome' or 'what comes out.'",
  "EVERY": "Old English æfre ælc, 'ever each.'",
  "FAITH": "Latin fides, 'trust.'",
  "FALSE": "Latin falsus, 'feigned.'",
  "FAUNA": "Roman goddess of country life, sister of Faunus. Used by Linnaeus for animal life.",
  "FENCE": "Short for defense. The Middle English form was fens.",
  "FEVER": "Latin febris, 'heat of illness.'",
  "FIELD": "Old English feld, 'open country.'",
  "FIRST": "Old English fyrst, a superlative of fore.",
  "FLAME": "Latin flamma, 'blazing fire.'",
  "FLASH": "Probably imitative of a sudden burst of light or sound.",
  "FLOAT": "Old English flotian, related to 'fleet.'",
  "FLOUR": "Originally 'flower of the wheat,' meaning the finest part.",
  "FOCUS": "Latin focus, 'hearth, fireplace.' Kepler used it for the point of an ellipse.",
  "FOREST": "Latin foris, 'outside,' meaning land outside the cultivated area.",
  "FRESH": "Old French freis, 'cool, recent.'",
  "FRIAR": "Latin frater, 'brother.'",
  "FRUIT": "Latin fructus, 'enjoyment, produce of the soil.'",
  "GAUGE": "Old North French gauge, a standard measure.",
  "GHOST": "Old English gast, 'spirit, breath.'",
  "GIANT": "Greek gigas, 'one of the earth-born.'",
  "GLADE": "Old English glæd, 'bright,' for an open sunny clearing in a forest.",
  "GLASS": "Old English glæs, related to amber and the color green.",
  "GOOSE": "Old English gos, an ancient bird name shared across Indo-European.",
  "GRACE": "Latin gratia, 'pleasing quality, favor.'",
  "GRADE": "Latin gradus, 'step.'",
  "GRAIN": "Latin granum, 'seed.'",
  "GRAPE": "Old French grape, 'bunch of grapes,' originally a hook for picking.",
  "GREEN": "Old English grene, 'growing, fresh.'",
  "GUEST": "Old Norse gestr, 'stranger.'",
  "HAPPY": "From hap, 'chance,' so 'happy' once meant 'lucky.'",
  "HEART": "Old English heorte, an ancient body word found across Indo-European languages.",
  "HONEY": "Old English hunig.",
  "HORSE": "Old English hors, replacing the older eoh.",
  "HOTEL": "French hôtel, from Latin hospitale, 'guest-house.'",
  "HOUSE": "Old English hus, common across Germanic languages.",
  "HUMAN": "Latin humanus, related to humus, 'earth.' The earth-creature.",
  "IMAGE": "Latin imago, 'likeness, copy.'",
  "INDEX": "Latin index, 'pointer, forefinger.'",
  "IVORY": "Latin ebur, the elephant tusk.",
  "JEWEL": "Old French juel, possibly from Latin iocus, 'plaything.'",
  "JUICE": "Latin ius, 'broth, sauce.'",
  "KAYAK": "From Inuktitut qajaq, the small skin boat.",
  "KIOSK": "Turkish köşk, 'pavilion or summerhouse.'",
  "KNIFE": "Old Norse knifr.",
  "KOALA": "From Dharug gula, the Aboriginal word for the tree-climbing marsupial.",
  "LASER": "Acronym from 1960. Light Amplification by Stimulated Emission of Radiation.",
  "LEARN": "Old English leornian, 'to get knowledge.'",
  "LEMON": "Persian limun, through Arabic and Old French.",
  "LIGHT": "Old English leoht, both 'illumination' and 'not heavy' from different roots.",
  "LLAMA": "Spanish from Quechua llama, the Andean pack animal.",
  "LOGIC": "Greek logike, from logos, 'word, reason.'",
  "LUNAR": "Latin luna, 'moon.'",
  "MAGIC": "Greek magike, from the Magi, the Persian priestly caste.",
  "MAIZE": "From Taino mahiz, the Caribbean word for corn.",
  "MANGO": "From Tamil mankay, through Portuguese.",
  "MAPLE": "Old English mapul, the broad-leafed tree.",
  "MEDAL": "Italian medaglia, originally a small coin.",
  "MELON": "Greek melopepon, 'apple-gourd.'",
  "METAL": "Greek metallon, 'mine, mineral.'",
  "MIGHT": "Old English miht, 'power.'",
  "MOCHA": "From Mocha, the Yemeni port that exported coffee.",
  "MONEY": "Latin moneta, 'mint,' from the temple where Roman coins were made.",
  "MONTH": "Old English monath, originally tied to the moon's cycle.",
  "MOTOR": "Latin motor, 'mover.'",
  "MOUNT": "Latin mons, 'mountain.'",
  "MOUSE": "Old English mus, an ancient body of words shared with Latin and Sanskrit.",
  "MUSIC": "Greek mousike, 'art of the Muses.'",
  "NIGHT": "Old English niht, related to Latin nox.",
  "NOBLE": "Latin nobilis, 'well-known.'",
  "NORTH": "Old English north, the direction of the polar star.",
  "NOVEL": "Latin novellus, 'new little thing.'",
  "OCEAN": "Greek Okeanos, the river thought to encircle the earth.",
  "OLIVE": "Latin oliva, the Mediterranean fruit.",
  "OPERA": "Italian opera, 'work,' short for opera in musica.",
  "ORDER": "Latin ordo, 'a row or rank.'",
  "ORGAN": "Greek organon, 'tool, instrument.'",
  "PANIC": "From the Greek god Pan, who caused sudden fear in lonely places.",
  "PAPER": "Latin papyrus, the Egyptian reed.",
  "PASTA": "Italian pasta, 'paste, dough.'",
  "PEACE": "Latin pax, 'agreement, treaty.'",
  "PEACH": "From Latin persicum, 'Persian apple.'",
  "PENCE": "Old English penig, the small coin.",
  "PIANO": "Short for pianoforte, Italian for 'soft and loud.'",
  "PIZZA": "Italian pizza, attested since the 1500s, of disputed deeper origin.",
  "PLACE": "Latin platea, 'broad street or open space.'",
  "PLANT": "Latin planta, 'sole of the foot,' since seedlings were pressed in by foot.",
  "POETS": "Greek poietes, 'maker,' from poiein, 'to make.'",
  "POINT": "Latin punctum, 'a prick, a small spot.'",
  "POWER": "Old French povoir, 'to be able.'",
  "PRINT": "Old French preinte, 'an impression.'",
  "QUEEN": "Old English cwen, originally 'wife' or 'woman.'",
  "QUEST": "Latin quaerere, 'to seek.'",
  "QUOTE": "Latin quotare, 'to mark with chapter and verse.'",
  "RADAR": "Acronym from 1941. Radio Detection and Ranging.",
  "RADIO": "Latin radius, 'ray,' as in radio wave.",
  "RIVER": "Old French rivere, from Latin riparius, 'belonging to a riverbank.'",
  "ROBOT": "Czech robota, 'forced labor,' coined in Karel Čapek's 1920 play R.U.R.",
  "ROYAL": "Latin regalis, 'kingly.'",
  "SAFER": "Old French sauf, from Latin salvus, 'whole, healthy.'",
  "SALAD": "From Latin sal, 'salt,' since early salads were salted greens.",
  "SAUCE": "Latin salsus, 'salted.'",
  "SCARF": "Old North French escarpe, 'sash.'",
  "SCENT": "Latin sentire, 'to perceive.'",
  "SCHOOL": "Greek schole, originally 'leisure.' Where free citizens spent their free time.",
  "SCORE": "Old Norse skor, 'a notch,' since tallies were cut on sticks in groups of twenty.",
  "SHARK": "Origin unknown. Possibly from German Schurke, 'scoundrel.'",
  "SHIRT": "Old English scyrte, related to 'short.'",
  "SHORE": "Middle Low German schore, 'edge.'",
  "SLEEP": "Old English slæpan, common across Germanic languages.",
  "SMILE": "Middle English smilen, related to Latin mirari, 'to wonder.'",
  "SMOKE": "Old English smoca.",
  "SNAKE": "Old English snaca, from a root meaning 'to crawl.'",
  "SOLAR": "Latin sol, 'sun.'",
  "SOLID": "Latin solidus, 'firm, whole.'",
  "SOUND": "Latin sonus, 'noise.'",
  "SPACE": "Latin spatium, 'room, area.'",
  "SPELL": "Old English spell, 'speech, story.'",
  "SPICE": "Latin species, 'kind, sort,' from species of dried plants.",
  "STARK": "Old English stearc, 'stiff, severe.'",
  "STEEL": "Old English style, the worked iron.",
  "STONE": "Old English stan.",
  "STORM": "Old English storm, common across Germanic.",
  "STORY": "Old French estorie, from Latin historia.",
  "SUGAR": "From Sanskrit sharkara, through Arabic sukkar.",
  "SUSHI": "Japanese, literally 'sour rice,' since the rice is vinegared.",
  "TABLE": "Latin tabula, 'plank, flat surface.'",
  "TASTE": "Old French taster, 'to feel, touch.'",
  "TEACH": "Old English tæcan, 'to show.'",
  "TENOR": "Latin tenere, 'to hold,' since the tenor held the main melody.",
  "TIGER": "Greek tigris, possibly from a Persian word for 'arrow,' for its speed.",
  "TITLE": "Latin titulus, 'inscription, label.'",
  "TOAST": "Latin tostus, 'parched, dried by heat.'",
  "TODAY": "Old English to dæge, 'on this day.'",
  "TOOTH": "Old English toth.",
  "TOTEM": "From Ojibwe doodem, a clan symbol.",
  "TOUCH": "Old French tochier, ultimately imitative of a tap.",
  "TOWER": "Latin turris, 'high structure.'",
  "TOXIC": "Greek toxikon, 'poison for arrows,' from toxon, 'bow.'",
  "TRACK": "Old French trac, 'a trace or footprint.'",
  "TRADE": "Old English trod, 'a path,' originally the route a merchant took.",
  "TRAIN": "Latin trahere, 'to drag, to draw.'",
  "TREND": "Old English trendan, 'to roll, turn.'",
  "TRUCK": "Possibly from Greek trochos, 'wheel.'",
  "TRUST": "Old Norse traust, 'help, confidence.'",
  "TRUTH": "Old English treowth, 'faithfulness.'",
  "ULTRA": "Latin ultra, 'beyond.'",
  "UNDER": "Old English under, an ancient direction word.",
  "UNION": "Latin unus, 'one.'",
  "UNITY": "Latin unitas, 'oneness.'",
  "URBAN": "Latin urbanus, 'belonging to the city.'",
  "USAGE": "Old French usage, from Latin usus, 'a use.'",
  "USUAL": "Latin usualis, 'ordinary.'",
  "VALUE": "Latin valere, 'to be worth, to be strong.'",
  "VAULT": "Latin volutus, 'rolled, arched.'",
  "VIDEO": "Latin video, 'I see.'",
  "VIRUS": "Latin virus, 'poison, slimy liquid.'",
  "VOICE": "Latin vox, the sound and the right to speak.",
  "WALTZ": "German Walzer, from walzen, 'to roll or revolve.'",
  "WATER": "Old English wæter, an ancient word found across Indo-European.",
  "WHALE": "Old English hwæl.",
  "WHEAT": "Old English hwæte, related to 'white' for the pale grain.",
  "WHITE": "Old English hwit.",
  "WHOLE": "Old English hal, 'healthy, intact.' Same root as 'heal.'",
  "WORLD": "Old English weoruld, 'age of man,' from wer ('man') + eld ('age').",
  "WORTH": "Old English weorth, 'valuable.'",
  "WRITE": "Old English writan, originally 'to scratch or carve.'",
  "YACHT": "Dutch jacht, 'hunting ship,' a fast vessel for chasing pirates.",
  "YEARN": "Old English giernan, 'to be eager.'",
  "YOUNG": "Old English geong.",
  "YOUTH": "Old English geoguth.",
  "ZEBRA": "Possibly from a Portuguese word for a wild ass, applied to the striped horse."
};
