const gameWords = [
  { word: "AIMER", definition: "to love", lesson: "AIMER means 'to love'. Example: 'J'aime ma famille de tout mon cœur.' (Translation: 'I love my family with all my heart.')" },
  { word: "AMOUR", definition: "love", lesson: "AMOUR means love. Example: 'L'amour est la plus belle des émotions.' (Translation: 'Love is the most beautiful of emotions.')" },
  { word: "ARBRE", definition: "tree", lesson: "ARBRE means tree. Example: 'L'arbre du parc est majestueux.' (Translation: 'The tree in the park is majestic.')" },
  { word: "AVION", definition: "airplane", lesson: "AVION means airplane. Example: 'L'avion décolle à l'heure prévue.' (Translation: 'The airplane takes off at the scheduled time.')" },
  { word: "ACIER", definition: "steel", lesson: "ACIER means steel. Example: 'La structure en acier soutient le pont.' (Translation: 'The steel structure supports the bridge.')" },
  { word: "AGILE", definition: "agile", lesson: "AGILE means agile. Example: 'Le chat est très agile lorsqu'il saute.' (Translation: 'The cat is very agile when it jumps.')" },
  { word: "BALAI", definition: "broom", lesson: "BALAI means broom. Example: 'Elle balaie le sol avec son balai.' (Translation: 'She sweeps the floor with her broom.')" },
  { word: "BANAL", definition: "banal", lesson: "BANAL means banal. Example: 'Cette conversation est plutôt banale.' (Translation: 'This conversation is rather banal.')" },
  { word: "BELLE", definition: "beautiful", lesson: "BELLE means beautiful. Example: 'La femme est belle dans sa robe élégante.' (Translation: 'The woman is beautiful in her elegant dress.')" },
  { word: "BLANC", definition: "white", lesson: "BLANC means white. Example: 'La neige est d'un blanc éclatant.' (Translation: 'The snow is brilliantly white.')" },
  { word: "BOIRE", definition: "to drink", lesson: "BOIRE means 'to drink'. Example: 'Je vais boire un verre d'eau.' (Translation: 'I am going to drink a glass of water.')" },
  { word: "BOCAL", definition: "jar", lesson: "BOCAL means jar. Example: 'Le bocal de confiture est posé sur l'étagère.' (Translation: 'The jar of jam sits on the shelf.')" },
  { word: "CACHE", definition: "hide/cache", lesson: "CACHE means to hide or cache. Example: 'Il cache ses affaires dans le grenier.' (Translation: 'He hides his belongings in the attic.')" },
  { word: "CALME", definition: "calm", lesson: "CALME means calm. Example: 'Le lac est d'une tranquillité calme ce matin.' (Translation: 'The lake is calm and peaceful this morning.')" },
  { word: "CAPOT", definition: "hood", lesson: "CAPOT means hood. Example: 'Le capot de la voiture est ouvert pour la réparation.' (Translation: 'The car hood is open for repairs.')" },
  { word: "CARTE", definition: "card/map", lesson: "CARTE means card or map. Example: 'J'ai consulté la carte pour trouver le chemin.' (Translation: 'I consulted the map to find the way.')" },
  { word: "CAUSE", definition: "cause", lesson: "CAUSE means cause. Example: 'La cause de son succès est sa détermination.' (Translation: 'The cause of his success is his determination.')" },
  { word: "CHAUD", definition: "hot", lesson: "CHAUD means hot. Example: 'Le café est très chaud ce matin.' (Translation: 'The coffee is very hot this morning.')" },
  { word: "CHIEN", definition: "dog", lesson: "CHIEN means dog. Example: 'Le chien court après sa balle dans le jardin.' (Translation: 'The dog runs after its ball in the garden.')" },
  { word: "CITER", definition: "to quote", lesson: "CITER means 'to quote'. Example: 'Il aime citer des proverbes célèbres.' (Translation: 'He likes to quote famous proverbs.')" },
  { word: "CLAIR", definition: "clear", lesson: "CLAIR means clear. Example: 'Le ciel est clair et bleu aujourd'hui.' (Translation: 'The sky is clear and blue today.')" },
  { word: "COEUR", definition: "heart", lesson: "COEUR means heart. Example: 'Elle a un cœur généreux et aimant.' (Translation: 'She has a generous and loving heart.')" },
  { word: "CORPS", definition: "body", lesson: "CORPS means body. Example: 'Un corps sain abrite un esprit sain.' (Translation: 'A healthy body hosts a healthy mind.')" },
  { word: "COURT", definition: "short", lesson: "COURT means short. Example: 'La jupe est trop courte pour l'hiver.' (Translation: 'The skirt is too short for winter.')" },
  { word: "CRUEL", definition: "cruel", lesson: "CRUEL means cruel. Example: 'Il a été accusé d'un comportement cruel.' (Translation: 'He was accused of cruel behavior.')" },
  { word: "DANSE", definition: "dance", lesson: "DANSE means dance. Example: 'Ils dansent avec passion lors de la soirée.' (Translation: 'They dance passionately at the party.')" },
  { word: "DENTS", definition: "teeth", lesson: "DENTS means teeth. Example: 'Ses dents brillent après le brossage.' (Translation: 'Her teeth shine after brushing.')" },
  { word: "DOIGT", definition: "finger", lesson: "DOIGT means finger. Example: 'Il se coupe le doigt en cuisinant.' (Translation: 'He cuts his finger while cooking.')" },
  { word: "DORME", definition: "sleeps", lesson: "DORME means 'sleeps'. Example: 'Le bébé dort paisiblement dans son berceau.' (Translation: 'The baby sleeps peacefully in its cradle.')" },
  { word: "DOUTE", definition: "doubt", lesson: "DOUTE means doubt. Example: 'Elle ne doute jamais de ses capacités.' (Translation: 'She never doubts her abilities.')" },
  { word: "DRAME", definition: "drama", lesson: "DRAME means drama. Example: 'La pièce de théâtre était un véritable drame.' (Translation: 'The play was a true drama.')" },
  { word: "ÉPICE", definition: "spice", lesson: "ÉPICE means spice. Example: 'J'ajoute une épice exotique à ce curry.' (Translation: 'I add an exotic spice to this curry.')" },
  { word: "EXIGE", definition: "demands", lesson: "EXIGE means demands. Example: 'Ce professeur exige le meilleur de ses étudiants.' (Translation: 'This teacher demands the best from his students.')" },
  { word: "FLEUR", definition: "flower", lesson: "FLEUR means flower. Example: 'La fleur éclot au printemps avec éclat.' (Translation: 'The flower blooms brilliantly in spring.')" },
  { word: "FOUET", definition: "whip", lesson: "FOUET means whip. Example: 'Le chef fouette la crème pour en faire une mousse légère.' (Translation: 'The chef whips the cream to make a light mousse.')" },
  { word: "FUMER", definition: "to smoke", lesson: "FUMER means 'to smoke'. Example: 'Il est interdit de fumer dans ce bâtiment.' (Translation: 'It is forbidden to smoke in this building.')" },
  { word: "FRUIT", definition: "fruit", lesson: "FRUIT means fruit. Example: 'Le fruit frais est délicieux et nourrissant.' (Translation: 'Fresh fruit is delicious and nutritious.')" },
  { word: "FABLE", definition: "fable", lesson: "FABLE means fable. Example: 'Cette fable transmet une morale intemporelle.' (Translation: 'This fable conveys a timeless moral lesson.')" },
  { word: "FAUTE", definition: "mistake", lesson: "FAUTE means mistake. Example: 'Tout le monde fait des fautes parfois.' (Translation: 'Everyone makes mistakes sometimes.')" },
  { word: "GAMIN", definition: "kid", lesson: "GAMIN means kid. Example: 'Le gamin joue joyeusement dans la rue.' (Translation: 'The kid plays joyfully in the street.')" },
  { word: "GARDE", definition: "guard", lesson: "GARDE means guard. Example: 'Le garde surveille l'entrée du musée.' (Translation: 'The guard watches the entrance of the museum.')" },
  { word: "GOMME", definition: "eraser", lesson: "GOMME means eraser. Example: 'J'efface mes erreurs avec une gomme neuve.' (Translation: 'I erase my mistakes with a new eraser.')" },
  { word: "GRÂCE", definition: "grace", lesson: "GRÂCE means grace. Example: 'Elle se déplace avec une grâce naturelle.' (Translation: 'She moves with natural grace.')" },
  { word: "GLACE", definition: "ice/ice cream", lesson: "GLACE means ice or ice cream. Example: 'J'adore déguster une glace en été.' (Translation: 'I love enjoying ice cream in summer.')" },
  { word: "HEURE", definition: "hour", lesson: "HEURE means hour. Example: 'Il est l'heure de partir pour l'école.' (Translation: 'It is time to leave for school.')" },
  { word: "HOMME", definition: "man", lesson: "HOMME means man. Example: 'Cet homme est respecté pour sa sagesse.' (Translation: 'This man is respected for his wisdom.')" },
  { word: "HIVER", definition: "winter", lesson: "HIVER means winter. Example: 'L'hiver est rigoureux dans cette région.' (Translation: 'Winter is harsh in this region.')" },
  { word: "IMAGE", definition: "image", lesson: "IMAGE means image. Example: 'L'image projetée était d'une grande qualité.' (Translation: 'The projected image was of high quality.')" },
  { word: "IDÉAL", definition: "ideal", lesson: "IDÉAL means ideal. Example: 'C'est l'endroit idéal pour se détendre.' (Translation: 'It is the ideal place to relax.')" },
  { word: "JOUER", definition: "to play", lesson: "JOUER means 'to play'. Example: 'Les enfants aiment jouer dans le parc.' (Translation: 'Children love to play in the park.')" },
  { word: "JEUDI", definition: "Thursday", lesson: "JEUDI means Thursday. Example: 'Nous avons une réunion jeudi après-midi.' (Translation: 'We have a meeting on Thursday afternoon.')" },
  { word: "JOLIE", definition: "pretty", lesson: "JOLIE means pretty. Example: 'La fleur est jolie et délicate.' (Translation: 'The flower is pretty and delicate.')" },
  { word: "JANTE", definition: "rim", lesson: "JANTE means rim. Example: 'La jante de cette voiture est en alliage.' (Translation: 'The rim of this car is made of alloy.')" },
  { word: "KEBAB", definition: "kebab", lesson: "KEBAB means kebab. Example: 'Nous avons dégusté un kebab épicé ce soir.' (Translation: 'We enjoyed a spicy kebab tonight.')" },
  { word: "KARMA", definition: "karma", lesson: "KARMA means karma. Example: 'Son karma l'a poussé vers le succès.' (Translation: 'His karma pushed him toward success.')" },
  { word: "LIVRE", definition: "book", lesson: "LIVRE means book. Example: 'Je lis un livre captivant sur l'histoire.' (Translation: 'I am reading a captivating book about history.')" },
  { word: "LOUER", definition: "to rent", lesson: "LOUER means 'to rent'. Example: 'Ils vont louer un appartement en centre-ville.' (Translation: 'They are going to rent an apartment downtown.')" },
  { word: "LOURD", definition: "heavy", lesson: "LOURD means heavy. Example: 'Ce sac est vraiment lourd à porter.' (Translation: 'This bag is really heavy to carry.')" },
  { word: "LISSE", definition: "smooth", lesson: "LISSE means smooth. Example: 'Le tissu est doux et lisse au toucher.' (Translation: 'The fabric is soft and smooth to the touch.')" },
  { word: "LUTTE", definition: "fight", lesson: "LUTTE means fight. Example: 'Ils se préparent pour une lutte acharnée.' (Translation: 'They are preparing for a fierce fight.')" },
  { word: "LIANE", definition: "vine", lesson: "LIANE means vine. Example: 'La liane s'enroule autour de l'arbre.' (Translation: 'The vine wraps around the tree.')" },
  { word: "LUNDI", definition: "Monday", lesson: "LUNDI means Monday. Example: 'Lundi marque le début de la semaine de travail.' (Translation: 'Monday marks the start of the work week.')" },
  { word: "LASER", definition: "laser", lesson: "LASER means laser. Example: 'Le laser est utilisé dans de nombreuses technologies modernes.' (Translation: 'The laser is used in many modern technologies.')" },
  { word: "MAMAN", definition: "mom", lesson: "MAMAN means mom. Example: 'Ma maman prépare toujours un délicieux repas.' (Translation: 'My mom always prepares a delicious meal.')" },
  { word: "MERCI", definition: "thanks", lesson: "MERCI means thanks. Example: 'Je dis merci pour toute l'aide reçue.' (Translation: 'I say thanks for all the help received.')" },
  { word: "MORDU", definition: "bitten", lesson: "MORDU means bitten. Example: 'Le chien a mordu le jouet par accident.' (Translation: 'The dog accidentally bit the toy.')" },
  { word: "MERLE", definition: "blackbird", lesson: "MERLE means blackbird. Example: 'Le merle chante dans le jardin chaque matin.' (Translation: 'The blackbird sings in the garden every morning.')" },
  { word: "MELON", definition: "melon", lesson: "MELON means melon. Example: 'Le melon est juteux et rafraîchissant en été.' (Translation: 'The melon is juicy and refreshing in summer.')" },
  { word: "MOTIF", definition: "motif", lesson: "MOTIF means motif. Example: 'Le motif de ce tissu est très élégant.' (Translation: 'The motif of this fabric is very elegant.')" },
  { word: "MOULU", definition: "milled", lesson: "MOULU means milled. Example: 'La farine moulue est idéale pour la pâtisserie.' (Translation: 'The milled flour is ideal for baking.')" },
  { word: "MENER", definition: "to lead", lesson: "MENER means 'to lead'. Example: 'Elle sait mener son équipe avec assurance.' (Translation: 'She knows how to lead her team confidently.')" },
  { word: "NAGER", definition: "to swim", lesson: "NAGER means 'to swim'. Example: 'Ils aiment nager dans la mer en été.' (Translation: 'They love to swim in the sea during summer.')" },
  { word: "NAVET", definition: "turnip", lesson: "NAVET means turnip. Example: 'Le navet est un légume-racine commun en hiver.' (Translation: 'The turnip is a common root vegetable in winter.')" },
  { word: "NEIGE", definition: "snow", lesson: "NEIGE means snow. Example: 'La neige recouvre le paysage en hiver.' (Translation: 'Snow covers the landscape in winter.')" },
  { word: "NOBLE", definition: "noble", lesson: "NOBLE means noble. Example: 'Il est reconnu pour son caractère noble.' (Translation: 'He is known for his noble character.')" },
  { word: "NOTER", definition: "to note", lesson: "NOTER means 'to note'. Example: 'N'oublie pas de noter les informations importantes.' (Translation: 'Don't forget to note the important information.')" },
  { word: "NOYER", definition: "to drown", lesson: "NOYER means 'to drown'. Example: 'Il risque de noyer s'il ne fait pas attention.' (Translation: 'He risks drowning if he is not careful.')" },
  { word: "OBJET", definition: "object", lesson: "OBJET means object. Example: 'Cet objet ancien attire beaucoup d'attention.' (Translation: 'This antique object attracts a lot of attention.')" },
  { word: "ORAGE", definition: "storm", lesson: "ORAGE means storm. Example: 'L'orage éclate soudainement dans le ciel.' (Translation: 'The storm breaks out suddenly in the sky.')" },
  { word: "OUIJA", definition: "ouija board", lesson: "OUIJA means ouija board. Example: 'Ils ont utilisé une planche Ouija pour communiquer avec l'inconnu.' (Translation: 'They used an ouija board to communicate with the unknown.')" },
  { word: "ORDRE", definition: "order", lesson: "ORDRE means order. Example: 'L'ordre règne dans cette institution.' (Translation: 'Order reigns in this institution.')" },
  { word: "OLIVE", definition: "olive", lesson: "OLIVE means olive. Example: 'Les olives de Provence sont renommées.' (Translation: 'The olives from Provence are renowned.')" },
  { word: "OMBRE", definition: "shadow", lesson: "OMBRE means shadow. Example: 'L'ombre des arbres offre un refuge frais.' (Translation: 'The shadow of the trees provides a cool shelter.')" },
  { word: "POMME", definition: "apple", lesson: "POMME means apple. Example: 'La pomme est croquante et juteuse.' (Translation: 'The apple is crisp and juicy.')" },
  { word: "PIANO", definition: "piano", lesson: "PIANO means piano. Example: 'Le piano résonne avec une mélodie envoûtante.' (Translation: 'The piano resonates with an enchanting melody.')" },
  { word: "PISTE", definition: "track/path", lesson: "PISTE means track or path. Example: 'La piste de course traverse la campagne.' (Translation: 'The race track runs through the countryside.')" },
  { word: "PORTE", definition: "door", lesson: "PORTE means door. Example: 'Ferme la porte en sortant, s'il te plaît.' (Translation: 'Close the door when you leave, please.')" },
  { word: "PLUIE", definition: "rain", lesson: "PLUIE means rain. Example: 'La pluie tombe doucement sur le toit.' (Translation: 'The rain falls softly on the roof.')" },
  { word: "PETIT", definition: "small", lesson: "PETIT means small. Example: 'Le chaton est vraiment petit et mignon.' (Translation: 'The kitten is really small and cute.')" },
  { word: "PÂTES", definition: "pasta", lesson: "PÂTES means pasta. Example: 'J'adore manger des pâtes avec une sauce savoureuse.' (Translation: 'I love eating pasta with a tasty sauce.')" },
  { word: "POINT", definition: "point", lesson: "POINT means point. Example: 'Chaque point de son discours était convaincant.' (Translation: 'Every point of his speech was convincing.')" },
  { word: "PLOMB", definition: "lead (metal)", lesson: "PLOMB means lead (metal). Example: 'Le plomb est un métal très dense.' (Translation: 'Lead is a very dense metal.')" },
  { word: "PRIER", definition: "to pray", lesson: "PRIER means 'to pray'. Example: 'Ils se réunissent pour prier chaque soir.' (Translation: 'They gather to pray every evening.')" },
  { word: "PRUNE", definition: "plum", lesson: "PRUNE means plum. Example: 'La prune mûrit lentement sous le soleil.' (Translation: 'The plum ripens slowly under the sun.')" },
  { word: "QUAND", definition: "when", lesson: "QUAND means when. Example: 'Dis-moi quand tu seras prêt.' (Translation: 'Tell me when you are ready.')" },
  { word: "QUASI", definition: "almost", lesson: "QUASI means almost. Example: 'Le travail est quasi terminé, il manque quelques finitions.' (Translation: 'The work is almost finished, only a few touches remain.')" },
  { word: "RÊVER", definition: "to dream", lesson: "RÊVER means 'to dream'. Example: 'Je rêve d'un monde meilleur.' (Translation: 'I dream of a better world.')" },
  { word: "ROUGE", definition: "red", lesson: "ROUGE means red. Example: 'La rose rouge symbolise la passion.' (Translation: 'The red rose symbolizes passion.')" },
  { word: "RIVAL", definition: "rival", lesson: "RIVAL means rival. Example: 'Il affronte son rival sur le terrain de sport.' (Translation: 'He faces his rival on the sports field.')" },
  { word: "RIMER", definition: "to rhyme", lesson: "RIMER means 'to rhyme'. Example: 'Les poètes aiment rimer leurs vers.' (Translation: 'Poets love to rhyme their verses.')" },
  { word: "ROUTE", definition: "road", lesson: "ROUTE means road. Example: 'La route serpente à travers la campagne.' (Translation: 'The road winds through the countryside.')" },
  { word: "RURAL", definition: "rural", lesson: "RURAL means rural. Example: 'La vie rurale est simple et authentique.' (Translation: 'Rural life is simple and authentic.')" },
  { word: "RADAR", definition: "radar", lesson: "RADAR means radar. Example: 'Le radar surveille la vitesse sur l'autoroute.' (Translation: 'The radar monitors speed on the highway.')" },
  { word: "RESTE", definition: "remain", lesson: "RESTE means remain. Example: 'Après le dîner, il reste toujours un peu de dessert.' (Translation: 'After dinner, a little dessert always remains.')" },
  { word: "ROSES", definition: "roses", lesson: "ROSES means roses. Example: 'Les roses rouges embaument le jardin.' (Translation: 'The red roses perfume the garden.')" },
  { word: "SALUT", definition: "hi/hello", lesson: "SALUT means hi/hello. Example: 'Salut, comment vas-tu aujourd'hui?' (Translation: 'Hi, how are you today?')" },
  { word: "SABLE", definition: "sand", lesson: "SABLE means sand. Example: 'Le sable chaud s'étale sur la plage.' (Translation: 'The warm sand spreads out on the beach.')" },
  { word: "SINGE", definition: "monkey", lesson: "SINGE means monkey. Example: 'Le singe grimpe agilement aux arbres.' (Translation: 'The monkey climbs the trees agilely.')" },
  { word: "SUITE", definition: "next/following", lesson: "SUITE means next or following. Example: 'La suite de la série sera diffusée demain.' (Translation: 'The next episode of the series will air tomorrow.')" },
  { word: "SUEUR", definition: "sweat", lesson: "SUEUR means sweat. Example: 'La sueur perle sur son front après l'effort.' (Translation: 'Sweat beads on his forehead after the effort.')" },
  { word: "SÉRIE", definition: "series", lesson: "SÉRIE means series. Example: 'J'adore regarder cette série captivante.' (Translation: 'I love watching this captivating series.')" },
  { word: "SOLDE", definition: "discount/balance", lesson: "SOLDE means discount or balance. Example: 'Les soldes d'été commencent cette semaine.' (Translation: 'The summer sales start this week.')" },
  { word: "SOMME", definition: "sum", lesson: "SOMME means sum. Example: 'La somme des chiffres donne le résultat final.' (Translation: 'The sum of the numbers gives the final result.')" },
  { word: "SUCRE", definition: "sugar", lesson: "SUCRE means sugar. Example: 'Ajoute un peu de sucre dans ton café.' (Translation: 'Add a little sugar to your coffee.')" },
  { word: "TABLE", definition: "table", lesson: "TABLE means table. Example: 'La table est dressée pour le dîner.' (Translation: 'The table is set for dinner.')" },
  { word: "TEMPS", definition: "time", lesson: "TEMPS means time. Example: 'Le temps passe vite quand on s'amuse.' (Translation: 'Time flies when you're having fun.')" },
  { word: "TERRE", definition: "earth", lesson: "TERRE means earth. Example: 'La terre est fertile et pleine de vie.' (Translation: 'The earth is fertile and full of life.')" },
  { word: "TIGRE", definition: "tiger", lesson: "TIGRE means tiger. Example: 'Le tigre est un animal majestueux et puissant.' (Translation: 'The tiger is a majestic and powerful animal.')" },
  { word: "TISSU", definition: "fabric", lesson: "TISSU means fabric. Example: 'Ce tissu est doux et de haute qualité.' (Translation: 'This fabric is soft and of high quality.')" },
  { word: "TOMBE", definition: "tomb/falls", lesson: "TOMBE means tomb or falls. Example: 'La neige tombe doucement sur le sol.' (Translation: 'The snow falls gently on the ground.')" },
  { word: "TITRE", definition: "title", lesson: "TITRE means title. Example: 'Le livre a un titre captivant.' (Translation: 'The book has a captivating title.')" },
  { word: "TACHE", definition: "stain", lesson: "TACHE means stain. Example: 'Une tache de vin rouge a marqué la nappe.' (Translation: 'A red wine stain marked the tablecloth.')" },
  { word: "TRAIT", definition: "line/feature", lesson: "TRAIT means line or feature. Example: 'Les traits de son visage sont très expressifs.' (Translation: 'The features of her face are very expressive.')" },
  { word: "UTILE", definition: "useful", lesson: "UTILE means useful. Example: 'Cet outil est vraiment utile pour réparer la voiture.' (Translation: 'This tool is really useful for fixing the car.')" },
  { word: "UNION", definition: "union", lesson: "UNION means union. Example: 'L'union fait la force dans cette équipe.' (Translation: 'Union makes the team strong.')" },
  { word: "USAGE", definition: "usage", lesson: "USAGE means usage. Example: 'L'usage de ce mot est courant en français.' (Translation: 'The usage of this word is common in French.')" },
  { word: "VACHE", definition: "cow", lesson: "VACHE means cow. Example: 'La vache broute paisiblement dans le pré.' (Translation: 'The cow grazes peacefully in the meadow.')" },
  { word: "VOILE", definition: "sail/veil", lesson: "VOILE means sail or veil. Example: 'Le bateau déploie sa voile blanche.' (Translation: 'The boat unfurls its white sail.')" },
  { word: "VOCAL", definition: "vocal", lesson: "VOCAL means vocal. Example: 'Elle possède une voix vocale et puissante.' (Translation: 'She has a strong, resonant voice.')" },
  { word: "VIVRE", definition: "to live", lesson: "VIVRE means 'to live'. Example: 'Il est important de vivre pleinement chaque instant.' (Translation: 'It is important to live each moment to the fullest.')" },
  { word: "VALET", definition: "valet", lesson: "VALET means valet. Example: 'Le valet a pris soin de garer la voiture.' (Translation: 'The valet took care of parking the car.')" },
  { word: "VALSE", definition: "waltz", lesson: "VALSE means waltz. Example: 'Ils ont dansé une valse élégante lors du bal.' (Translation: 'They danced an elegant waltz at the ball.')" },
  { word: "VOTER", definition: "to vote", lesson: "VOTER means 'to vote'. Example: 'Les citoyens vont voter aux prochaines élections.' (Translation: 'The citizens will vote in the upcoming elections.')" },
  { word: "VOTRE", definition: "your", lesson: "VOTRE means your. Example: 'Votre avis est très important pour nous.' (Translation: 'Your opinion is very important to us.')" },
  { word: "WAGON", definition: "wagon", lesson: "WAGON means wagon. Example: 'Le wagon du train est rempli de passagers.' (Translation: 'The train wagon is filled with passengers.')" },
  { word: "XÉNON", definition: "xenon", lesson: "XÉNON means xenon. Example: 'Les phares au xénon éclairent la route la nuit.' (Translation: 'Xenon headlights illuminate the road at night.')" },
  { word: "YACHT", definition: "yacht", lesson: "YACHT means yacht. Example: 'Le yacht navigue sur la Méditerranée avec élégance.' (Translation: 'The yacht sails elegantly on the Mediterranean Sea.')" },
  { word: "ZÈBRE", definition: "zebra", lesson: "ZÈBRE means zebra. Example: 'Le zèbre se distingue par ses rayures uniques.' (Translation: 'The zebra is distinguished by its unique stripes.')" },
  { word: "ZESTE", definition: "zest", lesson: "ZESTE means zest. Example: 'Râpez le zeste d'un citron pour parfumer le plat.' (Translation: 'Grate the zest of a lemon to flavor the dish.')" },
  { word: "ARGON", definition: "argon (element)", lesson: "ARGON means argon (element). Example: 'L'argon est utilisé dans les lampes fluorescentes.' (Translation: 'Argon is used in fluorescent lamps.')" },
  { word: "BOULE", definition: "ball", lesson: "BOULE means ball. Example: 'Les enfants jouent avec une boule dans le parc.' (Translation: 'The children are playing with a ball in the park.')" },
  { word: "CIRER", definition: "to wax/polish", lesson: "CIRER means 'to wax' or polish. Example: 'Il aime cirer ses chaussures le dimanche.' (Translation: 'He likes to polish his shoes on Sundays.')" },
  { word: "DEUIL", definition: "mourning", lesson: "DEUIL means mourning. Example: 'La famille est en deuil après la perte d'un être cher.' (Translation: 'The family is in mourning after losing a loved one.')" },
  { word: "ENFIN", definition: "finally", lesson: "ENFIN means finally. Example: 'Enfin, le projet est terminé.' (Translation: 'Finally, the project is complete.')" },
  { word: "FENDU", definition: "split", lesson: "FENDU means split. Example: 'Le bois fend facilement avec une bonne hache.' (Translation: 'The wood splits easily with a good axe.')" },
  { word: "HÂLER", definition: "to tan", lesson: "HÂLER means 'to tan'. Example: 'Il aime hâler sur la plage pendant l'été.' (Translation: 'He likes to tan on the beach during summer.')" },
  { word: "PLIER", definition: "to fold", lesson: "PLIER means 'to fold'. Example: 'Plie soigneusement tes vêtements après la lessive.' (Translation: 'Fold your clothes carefully after laundry.')" },
  { word: "TONER", definition: "toner", lesson: "TONER means toner. Example: 'J'ai acheté du toner pour mon imprimante hier.' (Translation: 'I bought toner for my printer yesterday.')" },
  { word: "SATIN", definition: "satin", lesson: "SATIN means satin. Example: 'La robe en satin brille sous la lumière du soir.' (Translation: 'The satin dress shines under the evening light.')" },
  { word: "RUGBY", definition: "rugby", lesson: "RUGBY means rugby. Example: 'L'équipe de rugby s'est entraînée dur pour le match.' (Translation: 'The rugby team trained hard for the match.')" },
  { word: "ZOMBI", definition: "zombie", lesson: "ZOMBI means zombie. Example: 'Le film montre un monde envahi par des zombis.' (Translation: 'The film depicts a world overrun by zombies.')" }
];
